name: Shell commands
on: [push]
jobs:
  run-shell-command:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-20.04]
    steps:
      - name: afficehr une chaine de caratere
        run: echo "Hello world"
      - name; afficehr le repertoire courant
	run: pwd
      - name: multiline script
        run: |
          python3 -V
          touch my_file_with_workflow.py
          ls -l
